// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuebF8QWh0Lvoob-Te54t_qH9kUlDOAQ',
    appId: '1:1024426014345:web:2aac7c8488c84a7e833858',
    messagingSenderId: '1024426014345',
    projectId: 'new-project-9ccad',
    authDomain: 'new-project-9ccad.firebaseapp.com',
    storageBucket: 'new-project-9ccad.firebasestorage.app',
    measurementId: 'G-3WZ4654151',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGjEQSYV6aOWJHYQ-fjnB331B5r7jwwU',
    appId: '1:1024426014345:android:164a946f59692fb4833858',
    messagingSenderId: '1024426014345',
    projectId: 'new-project-9ccad',
    storageBucket: 'new-project-9ccad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-Zndskdo8m5Xb37fTHa0TaiLwmQDdqY',
    appId: '1:1024426014345:ios:386783534947f00d833858',
    messagingSenderId: '1024426014345',
    projectId: 'new-project-9ccad',
    storageBucket: 'new-project-9ccad.firebasestorage.app',
    iosBundleId: 'com.admin.attendance.adminAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-Zndskdo8m5Xb37fTHa0TaiLwmQDdqY',
    appId: '1:1024426014345:ios:386783534947f00d833858',
    messagingSenderId: '1024426014345',
    projectId: 'new-project-9ccad',
    storageBucket: 'new-project-9ccad.firebasestorage.app',
    iosBundleId: 'com.admin.attendance.adminAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2e19yTtvpnMO0rx5aF92M2c7S84dvgW0',
    appId: '1:1024426014345:web:1c17ecff08d7dc71833858',
    messagingSenderId: '1024426014345',
    projectId: 'new-project-9ccad',
    authDomain: 'new-project-9ccad.firebaseapp.com',
    storageBucket: 'new-project-9ccad.firebasestorage.app',
    measurementId: 'G-YQ5LS1C8V1',
  );
}
